### ISSUE TITLE
setvtrgb: fopen: No such file or directory

### ISSUE THREAD

**Issue by maxigaz** [coderonline/base16-vtrgb#1]
First of all, thank you for maintaining this repository! There's one thing I noticed while consulting the README.

I've just installed the AUR package under Arch Linux. When I run the command `setvtrgb vtrgb/base16-tomorrow` in a virtual console, I receive the following error message:

```
setvtrgb: fopen: No such file or directory
```

However, if I specify the full filename of any of the themes that are part of the package, it works fine:

```
cd /usr/share/kbd/consolecolors
setvtrgb base16-tomorrow.vga
```

Would it be a good idea to point this out in the README?

**Comment by coderonline** [comment]
Hi! Thanks for the feedback and you are absolutely about the documentation being inconclusive there. I will fix that with the next update.

**Comment by coderonline** [comment]
Finally fixed. Thanks again for reporting.
